'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Progress_savvy_animation.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Frame_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame 9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frame1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frame1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frame2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frame2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frame3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frame3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Red_30x30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red 30x30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reszied() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reszied", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
